// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc8z41ONS55nox4p4caZdJvn7HmaD5bkM',
    appId: '1:897794450857:web:7cf2a93a1fc713d4dc90b8',
    messagingSenderId: '897794450857',
    projectId: 'notes-bella',
    authDomain: 'notes-bella.firebaseapp.com',
    storageBucket: 'notes-bella.appspot.com',
    measurementId: 'G-K5EC7P7P5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdFLCkMH-UDETqWpIQJSgRyhl8DIyiKyQ',
    appId: '1:897794450857:android:7157bf156cc61060dc90b8',
    messagingSenderId: '897794450857',
    projectId: 'notes-bella',
    storageBucket: 'notes-bella.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHBNEwjLKJQhVXgnRsnViZhATbW6Dg6o4',
    appId: '1:897794450857:ios:59237e361a1fd810dc90b8',
    messagingSenderId: '897794450857',
    projectId: 'notes-bella',
    storageBucket: 'notes-bella.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHBNEwjLKJQhVXgnRsnViZhATbW6Dg6o4',
    appId: '1:897794450857:ios:59237e361a1fd810dc90b8',
    messagingSenderId: '897794450857',
    projectId: 'notes-bella',
    storageBucket: 'notes-bella.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc8z41ONS55nox4p4caZdJvn7HmaD5bkM',
    appId: '1:897794450857:web:b66cb02b201ab75adc90b8',
    messagingSenderId: '897794450857',
    projectId: 'notes-bella',
    authDomain: 'notes-bella.firebaseapp.com',
    storageBucket: 'notes-bella.appspot.com',
    measurementId: 'G-1GL8TMLSJP',
  );
}
